=== Cuuper22/ivc/research/data/open_prototype/nonlinguistic/sproat2014/corpora/corpora/mySchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!--  -->
	<xs:element name="collection">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="1" name="entry"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
<!--a bibliographic entry and all the documents found in that source  -->
	<xs:element name="entry">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" name="bib"/>
				<xs:element maxOccurs="unbounded" name="document" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
<!--page number, optional description, and the docText -->
	<xs:element name="document">
		<xs:complexType>
			<xs:all>
				<xs:element name="page" type="xs:string" minOccurs="0"/>
				<xs:element maxOccurs="1" minOccurs="0" name="description" type="xs:string"/>
				<xs:element name="docText"/>
			</xs:all>
			<xs:anyAttribute/>
		</xs:complexType>
	</xs:element>

	<xs:element name="bib">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="author" type="xs:string"/>
				<xs:element name="year" type="xs:string"/>
				<xs:element name="title" type="xs:string"/>
				<xs:element name="pubInfo" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
<!--actual text consisting of symbols, lines, circles, and/or symbolUnits  -->
	<xs:element name="docText">
		<xs:complexType>
				<xs:sequence>
					<xs:element minOccurs="0" name="description" type="xs:string"/>
					<xs:group maxOccurs="unbounded" ref="symbolGroup"/>
					<xs:choice/>
				</xs:sequence>
		</xs:complexType>
	</xs:element>
<!--contains "symbolGroup" to allow just symbols or the embedding of lines, circles, and symbolUnits  -->	
   <xs:element name="circle">
		<xs:complexType>
			<xs:group maxOccurs="unbounded" ref="symbolGroup"/>
		</xs:complexType>
	</xs:element>
<!--symbols can be grouped into lines, circles, or symbolUnits, or stand as a lone symbol.
    lines, circles, and symbolUnits can recursively embed other symbolGroup elements  -->	
	<xs:group name="symbolGroup">
		<xs:sequence>
		    <xs:element maxOccurs="unbounded" minOccurs="0" name="line"/>
		    <xs:element maxOccurs="unbounded" minOccurs="0" name="circle"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="symbol"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="symbolUnit"/>
			<xs:element minOccurs="0" name="description" type="xs:string"/>
			<xs:element minOccurs="0" name="src" type="xs:string"/>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="alternative"/>
		</xs:sequence>
	</xs:group>
	<!--splits a document into "lines" Lines must be labled with integers-->
	<xs:element name="line">
		<xs:complexType>
			<xs:group maxOccurs="unbounded" ref="symbolGroup"/>
			<xs:attribute name="number" type="lineType"/>
		</xs:complexType>
	</xs:element>
<!--splits a document into "sides" such as rock faces. 
    Sides must be labeled (A,B,C,D,recto,verso) char lables are neutral in order. 
    recto is known front side, and verso is known back side -->	
	<xs:element name="side">
		<xs:complexType>
			<xs:group maxOccurs="unbounded" ref="symbolGroup"/>
			<xs:attribute name="number" type="sideType"/>
		</xs:complexType>
	</xs:element>
	
<!-- can contain an alternative title, a title and src tag, or an entire alternative unit(circle, line, symbolUnit) -->	
	<xs:element name="alternative">
	  <xs:complexType mixed="true">
		 <xs:choice>
		     <xs:element name="alternative" type="xs:string"/>
		     <!--group allows a symbol unit or circle, etc to have an alternative transcription -->
			 <xs:group maxOccurs="unbounded" ref="symbolGroup"/>
			 <xs:sequence>
			     <xs:element name="title" maxOccurs="unbounded" type="xs:string"/>
			     <xs:element name="src" type="xs:string"/>
			 </xs:sequence>
		 </xs:choice>
	  </xs:complexType>
	</xs:element>
	
<!--contains "symbolGroup" to allow just symbols or the embedding of lines, circles, and symbol units  -->	
	<xs:element name="symbolUnit">
		<xs:complexType>
			<xs:group maxOccurs="unbounded" ref="symbolGroup"/>
			<xs:anyAttribute/>
		</xs:complexType>
	</xs:element>
<!--alternatives can simply be a title, or it can have title and src tags inside it-->	
	<xs:element name="symbol">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="xs:string"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="alternative"/>
				<xs:element minOccurs="0" name="description" type="xs:string"/>
			</xs:sequence>
			<xs:anyAttribute/>
		</xs:complexType>
	</xs:element>
	<!--These are restricted values for "reliability" attribute-->	
	<xs:simpleType name="relType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="uncertain"/>
			<xs:enumeration value="fragment"/>
			<xs:enumeration value="alternative transcriptions"/>
		</xs:restriction>
	</xs:simpleType>
<!--numType: A,B,recto,verso,or any integer-->		
	<xs:simpleType name="numType"> 
		<xs:union memberTypes="sideType lineType"/>
	</xs:simpleType>
<!--This is the set of all integers for labeling lines for "numType"-->	
	<xs:simpleType name="lineType">
		 <xs:restriction base="xs:integer"/>
	</xs:simpleType>
<!--This is the set for labeling sides for "numType-->	
	<xs:simpleType name="sideType">
		 <xs:restriction base="xs:string">
			<xs:enumeration value="A"/>
			<xs:enumeration value="B"/>
			<xs:enumeration value="C"/>
			<xs:enumeration value="D"/>
			<xs:enumeration value="recto"/>
			<xs:enumeration value="verso"/>		
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="totemPole"/>
			<xs:enumeration value="Vinča"/>
			<xs:enumeration value="PictishStone"/>
			<xs:enumeration value="Kudduru" />
		</xs:restriction>
	</xs:simpleType>
<!--type,number, and reliability have simpleType restrictions-->
	<xs:attribute name="type" type="tType"/>
	<xs:attribute name="number" type="numType"/>
	<xs:attribute name="origin" type="xs:string"/>
	<xs:attribute name="reliability" type="relType"/>
	<xs:attribute name="id" type="xs:ID"/>
	<xs:attribute name="xref" type="xs:IDREF"/>
	<xs:attribute name="region" type="xs:string"/>
	<xs:attribute name="class" type="xs:string"/>
	<xs:attribute name="group" type="xs:string"/>
</xs:schema>

=== Cuuper22/ivc/research/data/open_prototype/nonlinguistic/sproat2014/corpora/corpora/Pictish.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mySchema.xsd">
   <entry>
		<bib>
			<author> University of Strathclyde Glasgow </author>
		    <year>   Retrieved 6/30, 2011   </year>
		    <title>  Pictish Stone Database.  </title>
		    <pubInfo> from http://www.mathstat.strath.ac.uk/outreach/pictish/database.php </pubInfo>
		</bib>
		
		<document type="PictishStone" region="Angus" class="I">
		    <description>Aberlemno 1</description>
		    <docText>
				<line number="1">
					<symbol><title>Serpent</title></symbol>
				</line>
				<line number="2">
					<symbolUnit>
						<symbol><title>Double-Disc</title></symbol>
						<symbol><title>Z</title></symbol>
					</symbolUnit>
				</line>
				<line number="3">
					<symbol><title>Mirror</title></symbol>
					<symbol><title>Comb</title></symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Angus" class="II">
		    <description>Aberlemno 2</description>
		    <docText>
				<line number="1">
					<symbolUnit>
						<symbol><title>Divided-Rectangle</title></symbol>
						<symbol><title>Z</title></symbol>
					</symbolUnit>
					<symbol reliability="alternative transcriptions">
						<title>Triple-Disc</title>
						<alternative><symbolUnit>
							<symbol><title>Triple-Disc</title></symbol>
							<symbol><title>Bar</title></symbol>
							<src>PSSH</src>
						</symbolUnit></alternative>
					</symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Angus" class="II">
		    <description>Aberlemno 3</description>
		    <docText>
				<line number="1">
					<symbolUnit>
						<symbol><title>Crescent</title></symbol>
						<symbol><title>V</title></symbol>
					</symbolUnit>
				</line>
				<line number="2">
					<symbolUnit>
						<symbol><title>Double-Disc</title></symbol>
						<symbol><title>Z</title></symbol>
					</symbolUnit>
				</line>
				<line number="3">
					<symbol reliability="uncertain"><title>Centaur</title></symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Angus" class="IV">
		    <description>Aberlemno 4</description>
		    <docText>
				<line number="1">
					<symbol reliability="uncertain"><title>Crescent</title></symbol>
				</line>
				<line number="2">
					<symbol reliability="alternative transcriptions">
						<title>Beast</title>
						<alternative><title>Curved-Line</title><src>PSSH, RCAHMS</src></alternative>
					</symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Angus" class="I">
		    <description>Aberlemno 5, Flemington Farm</description>
		    <docText>
				<line number="1">
					<symbol><title>Horseshoe</title><description>aka Arch</description></symbol>
				</line>
				<line number="2">
					<symbol><title>Beast</title></symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Perthshire and Kinross" class="I">
		    <description>Abernethy</description>
		    <docText>
				<line number="1">
					<symbol reliability="uncertain"><title>Hammer</title></symbol>
					<symbol reliability="alternative transcriptions">
						<title>Tuning-Fork</title>
						<description>aka Tongs</description>
						<alternative><title>Notched-Rectangle</title><src>Jackson</src></alternative>
						<alternativesrc>Jackson</alternativesrc>
					</symbol>
					<symbol reliability="uncertain"><title>Anvil</title></symbol>
				</line>
				<line number="2">
					<symbolUnit>
						<symbol><title>Crescent</title></symbol>
						<symbol><title>V</title></symbol>
					</symbolUnit>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Highland Caithness" class="I">
		    <description>Ackergill 1, Keiss Bay</description>
		    <docText>
				<line number="1">
					<symbol><title>Salmon</title></symbol>
				</line>
				<line number="2">
					<symbol><title>Rectangle</title></symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Highland Caithness" class="I">
		    <description>Ackergill 2</description>
		    <docText>
				<line number="1">
					<symbol reliability="alternative transcriptions">
						<title>Rectangle</title>
						<alternative><title>Nochted-Rectangle</title><src>PSSH, RCAHMS</src></alternative>
					</symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Highland Badenoch and Strathspey" class="I">
		    <description>Advie</description>
		    <docText>
				<line number="1">
					<symbolUnit>
						<symbol><title>Crescent</title></symbol>
						<symbol><title>V</title></symbol>
					</symbolUnit>
					<symbol><title>Mirror-Case</title></symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Perthshire and Kinross" class="II">
		    <description>Alyth</description>
		    <docText>
				<line number="1">
					<symbolUnit>
						<symbol><title>Double-Disc</title></symbol>
						<symbol><title>Z</title></symbol>
					</symbolUnit>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Dumfries and Galloway" class="I">
		    <description>Anwoth, Trusty's Hill</description>
		    <docText>
				<line number="1">
					<symbolUnit>
						<symbol><title>Double-Disc</title></symbol>
						<symbol><title>Z</title></symbol>
					</symbolUnit>
					<symbol reliability="uncertain"><title>Sword</title></symbol>
					<symbol><title>Fish-Monster</title><description>aka Seahorse</description></symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Highland Ross and Cromarty" class="IV">
		    <description>Arbirlot</description>
		    <docText>
				<line number="1">
					<symbol reliability="uncertain"><title>Book</title></symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Aberdeenshire" class="I">
		    <description>Ardiachie</description>
		    <docText>
				<line number="1">
					<symbol reliability="alternative transcriptions">
						<title>Wheel</title>
						<alternative><title>Spoked-Wheel</title><src>RCAHMS</src></alternative>
					</symbol>
				</line>
				<line number="2">
					<symbol reliability="uncertain"><title>Disc</title></symbol>
				</line>
				<line number="3">
					<symbol reliability="uncertain"><title>Step</title></symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Highland Ross and Cromarty" class="I">
		    <description>Ardliar, Kennethmont</description>
		    <docText>
				<line number="1">
					<symbol><title>Beast</title></symbol>
					<symbol reliability="alternative transcriptions">
						<title>Tuning-Fork</title>
						<alternative><title>Broken-Sword</title><src>PSSH</src></alternative>
						<alternative><title>Notched-Rectangle</title><src>Jackson</src></alternative>
					</symbol>
					<symbol><title>Mirror</title></symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Highland Ross and Cromarty" class="I">
		    <description>Ardross 1</description>
		    <docText>
				<line number="1">
					<symbol reliability="alternative transcriptions">
						<title>Wolf</title>
						<alternative><title>Bust-of-Deer</title><src>RCAHMS</src></alternative>
					</symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Moray" class="I">
		    <description>Ardross 2</description>
		    <docText>
				<line number="1">
					<symbol reliability="alternative transcriptions">
						<title>Deer</title>
						<alternative><title>Dog</title><src>RCAHMS</src></alternative>
						<alternative><title>Wolf</title><src>RCAHMS</src></alternative>
					</symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Angus" class="I">
		    <description>Arndilly</description>
		    <docText>
				<line number="1">
					<symbol><title>Mirror-Case</title></symbol>
					<symbolUnit>
						<symbol reliability="alternative transcriptions">
							<title>Notched-Rectangle</title>
							<alternative><title>Divided-Rectange</title><src>Field Guide</src></alternative>
							<alternative><title>Rectangle</title><src>Jakson</src></alternative>
						</symbol>
						<symbol><title>Z</title></symbol>
					</symbolUnit>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Angus" class="IV">
		    <description>Baggerton</description>
		    <docText>
				<line number="1">
					<symbolUnit>
						<symbol><title>Serpent</title></symbol>
						<symbol reliability="uncertain"><title>Z</title></symbol>
					</symbolUnit>
					<symbol reliability="uncertain"><title>Sceptre</title></symbol>
				</line>
		    </docText>
		</document>
		
		<document type="PictishStone" region="Highland Inverness" class="IV">
		    <description>Balblair, Monjack, Kilmorack</description>
		    <docText>
				<line number="1">
					<symbolUnit>
						<symbol><title>Man</title></symbol>
						<symbol reliability="alternative transcriptions">
							<title>Cub</title>
							<alternative><title>Sword</title><src>RCAHMS</src></alternative>
						</symbol>
					</symbolUnit>
				</line>
				<line number="2">
					<symbol reliability="uncertain"><title>Cupmarks</title></symbol>
				</line>
		    </docText>
		</document>
